### PR TITLE
fix: improves the ability to get all inline schemas and identify inline object schemas

### PR DESCRIPTION
**Pull request by TristanSpeakEasy**

### CODE REVIEW

**Comment by TristanSpeakEasy** [comment]
> 

Seems to be an unrelated bit of code dropping coverage not sure how to target it with a test as a summary with two different node structures confuses me tbh

**Review by daveshanley — APPROVED** [review]
LGTM!

**Comment by daveshanley** [comment]
I am not concerned about any 0.01% code change; I generally see these as blips and not something to be concerned about.

**Comment by TristanSpeakEasy** [comment]
> I am not concerned about any 0.01% code change; I generally see these as blips and not something to be concerned about.

Thanks @daveshanley ready to merge then :D

**Comment by daveshanley** [comment]
I can't merge it. Tells me there are conflicts?

Screenshot 2023-08-21 at 1 37 47 PM

**Comment by TristanSpeakEasy** [comment]
> I can't merge it. Tells me there are conflicts?
> 
> Screenshot 2023-08-21 at 1 37 47 PM

@daveshanley very strange I just double checked and there are no conflicts and I see this 
image

**Comment by daveshanley** [comment]
I can squash and merge, but I can't rebase. strange!

**Pull request merged**
