### PR TITLE
WIP: Consistent ordering of documentation

### PR DESCRIPTION
**Pull request by Baliedge**
https://github.com/pb33f/libopenapi/issues/119

Preserve order of paths as they were added to the document.
Utilize `github.com/wk8/go-ordered-map` instead of `map`.
* BREAKING CHANGE: This creates a breaking change around usage of `Paths` and `Schema` structures.  Use `orderedmap.OrderedMap` interface (`Get`/`Set`/`Len` methods) instead of `map` built-in.

Depends on:
* https://github.com/pb33f/libopenapi/pull/148

### CODE REVIEW

**Review by daveshanley — COMMENTED** [review]
Looking good so far, this is the correct way to build the feature. The only comments I really have are why the `MustGet` signature? Why not just `Get`? What am I missing?

**Comment by daveshanley** [comment]
Are we any closer to having this ready to go in?

**Comment by daveshanley** [comment]
@Baliedge Are you able to complete this work or will we need to take over the PR to pull it over the finish line?

**Comment by TristanSpeakEasy** [comment]
This has become critical to some upcoming work we have so I am going to see what it will take to pick up and get over the line. So @daveshanley or @Baliedge if you have any pointers on some keys areas that still need some work let me know otherwise I will move forward trying to address some of the "goals" we need to achieve with ordered maps, mainly:

- Support iterating through the high model in the same order as the OpenAPI document
- Render documents out deterministically
- Render documents out matching the original order (if just making light modifications to the document)
- Control the order of the rendered out docs, for example when the order of path items or components are specifically reordered
- Any maps stored within `example` or `examples` fields in schemas can maintain order both on read/write

**Comment by Baliedge** [comment]
@daveshanley @TristanSpeakEasy After some time using this code in our production codebase, I have some apprehension about the design used here and some design details could use consideration.  Most of your requirements are met with this PR with exceptions.  Mainly, I have these issues in mind:

- Weakly typed components, such as `examples`, don't properly use ordered maps.  Once an `orderdmap.Map` is marshaled to YAML, it unmarshals to `map` and breaks determinism.
  - While annoying, it hasn't been considered a showstopper issue for us.
- Refactoring existing data models defined in code from `map` to `orderedmap.Map` is very tedious.  Basic read/write access of `orderedmap.Map` objects is more tedious.  Is there a better design than enforcing a custom map type?
  - I see that the `low` models reference line numbers in each node, which helps keep determinism if used properly.
  - Perhaps the proper solution is a redesigned `high` model to eliminate use of `map`s entirely in favor of arrays (or ordered map).
  - Either way, this is a very heavy code change.

At the moment, I'm not comfortable asking for approval on this PR until these issues have been considered.

**Comment by TristanSpeakEasy** [comment]
Thanks @Baliedge some good points there.

> Weakly typed components, such as examples, don't properly use ordered maps. Once an orderdmap.Map is marshaled to YAML, it unmarshals to map and breaks determinism.
> While annoying, it hasn't been considered a showstopper issue for us.

For us this is actually one of the bigger show stoppers and on the "read" side we have a lot of nasty code to workaround this and on the write side we have no solution apart from post processing the yaml and sorting alphabetically but our customer's are annoyed at this as its breaking their intentions.

We have been thinking about an API for examples that basically makes it a union of the different "types" an example can be (ie object/map, array, primitive value) instead of just treating it as "any"

> Basic read/write access of orderedmap.Map objects is more tedious.

Agreed the interface is way less idiomatic but we have basically eaten this cost at the moment and have a lot of code all over the place that will take the high maps and convert it to an ordered map using the low line numbers of the key nodes to control insertion order into the ordered map.

So we already access everything via `.Get()` or iterate through the map using pairs and just accepted this as the cost of dealing with ordered data.

I'm not so sure treating this would be any less tedious as there is actually a lot of usage patterns where you do want to do key value lookups.

-----------------------------------------------------------------------

Personally for us we are happy enough with a switch to ordered maps in the high API as it larger removes some many gotchas when trying to deal with "existing" documents and we are building lots of tools that are trying to add value to the documents but in doing so at the moment we tend to have a lot of churn and diffs between the original doc and the modified one are just unwieldy and largely the features we are building are avoided because of the high churn in document structure.

I have just today been merging in the latest main to your branch and fixing some of the failing tests as if this PR landed for us it would be a measurable improvement both to our own code quality but would meet the expectations of our customers much more

**Comment by Baliedge** [comment]
@TristanSpeakEasy Thanks for the quick feedback.  I'm agreement with everything you've said. 
 Until now it was uncertain how acceptable all these breaking changes would be to the APIs due to the data type changes.

With all this understood, the only concerns I might have are edge cases where `maps` were neglected in the API and would result in additional future breaking changes once found.  Additional attention to unit testing could prevent this, but I'm at the disadvantage of not being the expert on OpenAPI spec and every API feature available in this tool.  Some oversight from your team on this would be beneficial.

Aside from that, I am done with my feature changes.

**Comment by Baliedge** [comment]
@TristanSpeakEasy Sure, fork it and do what you need.

**Comment by daveshanley** [comment]
There is no real way around the need to break the high level APIs in order to implement this feature. The design of the `NodeRenderer` uses the underlying low model to determine the order in which to render, so it will keep as much as it can in order, where there is data available. 

Once we have stable ordering / rendering coming from the high level model, this matures this feature and solves a lot of future functionality for the library.

**Comment by TristanSpeakEasy** [comment]
@Baliedge shall we close this PR?

**Pull request merged**
