### PR TITLE
Add RW Lock to allComponentSchemas to Prevent Data Race Error

### PR DESCRIPTION
**Pull request by califlower**
- solves issue #333 
- Accessing GetAllComponentSchemas causes a race condition error during usage. 
- Adds a RWLock to ensure that the map object is safely created across go routines. This pattern is used for other similar fields

### CODE REVIEW

**Comment by califlower** [comment]
I can add a test here, just wasn't sure about testing the race condition it was kind of difficult

**Comment by califlower** [comment]
I added a concurrent access test and a nil test. That should keep the coverage where it was at before

**Comment by califlower** [comment]
RIP. Doesn't seem like codecov is correct :<

**Comment by daveshanley** [comment]
The codecov is correct, I checked out your branch and this is what happens after running all tests. 

Screenshot 2024-10-29 at 10 30 30 AM

The problem is the test. 

```go
func TestSpecIndex_GetAllComponentSchemas_NilIndex(t *testing.T) {
	index := &SpecIndex{}
	schemas := index.GetAllComponentSchemas()
	assert.Nil(t, schemas, "Expected GetAllComponentSchemas to return nil when index is nil")
}```

`index` cannot be nil here, it will never be nil. To fix it: 

```go
func TestSpecIndex_GetAllComponentSchemas_NilIndex(t *testing.T) {
	var index *SpecIndex
	schemas := index.GetAllComponentSchemas()
	assert.Nil(t, schemas, "Expected GetAllComponentSchemas to return nil when index is nil")
}```

**Review by daveshanley — APPROVED** [review]
Thank you for your contribution.

**Comment by califlower** [comment]
Ah my bad. Thank you for fixing it and merging! Really appreciate it!

**Pull request merged**
